apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "xmrig.fullname" $ }}-config
  labels:
    app.kubernetes.io/name: {{ include "xmrig.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    helm.sh/chart: {{ include "xmrig.chart" $ }}
data:
  config.json: {{ .Values.config | toJson }}
  {{ end }}