# Default values for xmrig.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/dza89/xmrig
  pullPolicy: IfNotPresent
  tag:

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

config: |
  {
      "api": {
          "id": null,
          "worker-id": null
      },
      "http": {
          "enabled": false,
          "host": "127.0.0.1",
          "port": 0,
          "access-token": null,
          "restricted": true
      },
      "autosave": true,
      "background": false,
      "colors": true,
      "title": true,
      "randomx": {
          "init": -1,
          "init-avx2": -1,
          "mode": "auto",
          "1gb-pages": false,
          "rdmsr": true,
          "wrmsr": true,
          "cache_qos": false,
          "numa": true,
          "scratchpad_prefetch_mode": 1
      },
      "cpu": {
          "enabled": true,
          "huge-pages": true,
          "huge-pages-jit": false,
          "hw-aes": null,
          "priority": null,
          "memory-pool": false,
          "yield": true,
          "max-threads-hint": 100,
          "asm": true,
          "argon2-impl": null,
          "cn/0": false,
          "cn-lite/0": false
      },
      "opencl": {
          "enabled": false,
          "cache": true,
          "loader": null,
          "platform": "AMD",
          "adl": true,
          "cn/0": false,
          "cn-lite/0": false
      },
      "cuda": {
          "enabled": false,
          "loader": null,
          "nvml": true,
          "cn/0": false,
          "cn-lite/0": false
      },
      "donate-level": 1,
      "donate-over-proxy": 1,
      "log-file": null,
      "pools": [
          {
              "algo": null,
              "coin": null,
              "url": "donate.v2.xmrig.com:3333",
              "user": "YOUR_WALLET_ADDRESS",
              "pass": "x",
              "rig-id": null,
              "nicehash": false,
              "keepalive": false,
              "enabled": true,
              "tls": false,
              "tls-fingerprint": null,
              "daemon": false,
              "socks5": null,
              "self-select": null,
              "submit-to-origin": false
          }
      ],
      "print-time": 60,
      "health-print-time": 60,
      "dmi": true,
      "retries": 5,
      "retry-pause": 5,
      "syslog": false,
      "tls": {
          "enabled": false,
          "protocols": null,
          "cert": null,
          "cert_key": null,
          "ciphers": null,
          "ciphersuites": null,
          "dhparam": null
      },
      "dns": {
          "ipv6": false,
          "ttl": 30
      },
      "user-agent": null,
      "verbose": 0,
      "watch": true,
      "pause-on-battery": false,
      "pause-on-active": false
  }